namespace Nexus.GameEngine.GUI;

// BorderTemplate is auto-generated from [ComponentProperty] and [TemplateProperty] fields below

/// <summary>
/// Runtime border component that implements event-driven rendering behavior.
/// Templates configure the visual properties, runtime components subscribe to events and implement behavior.
/// </summary>
public partial class Border(IDescriptorManager descriptorManager)
    : Element(descriptorManager)
{
    // ComponentProperty fields - generator creates public properties with deferred updates
    [ComponentProperty]
    [TemplateProperty]
    private BorderStyle _style = BorderStyle.Rectangle;

    [ComponentProperty]
    [TemplateProperty]
    private Vector4D<float> _backgroundColor = Vector4D<float>.Zero; // Transparent (0,0,0,0)

    [ComponentProperty]
    [TemplateProperty]
    private Vector4D<float> _borderColor = new(0, 0, 0, 1); // Black (0,0,0,1)

    [ComponentProperty]
    [TemplateProperty]
    private Thickness _borderThickness = new(0);

    [ComponentProperty]
    [TemplateProperty]
    private float _cornerRadius = 0f;

    [ComponentProperty]
    [TemplateProperty]
    private string _backgroundImage = string.Empty;

    [ComponentProperty]
    [TemplateProperty]
    private string _borderImage = string.Empty;

    [ComponentProperty]
    [TemplateProperty]
    private float _opacity = 1.0f;

    // Properties are auto-generated by source generator from [TemplateProperty] fields above

    // Property change callbacks to trigger render updates
    partial void OnOpacityChanged(float oldValue)
    {
        // Clamp opacity to 0-1 range
        if (_opacity < 0.0f) _opacity = 0.0f;
        if (_opacity > 1.0f) _opacity = 1.0f;
        OnRenderPropertiesChanged();
    }

    /// <summary>
    /// Event fired when render properties change.
    /// </summary>
    public event EventHandler? RenderPropertiesChanged;

    /// <summary>
    /// Activate phase - Subscribe to required events.
    /// No interfaces needed - components self-register for events they care about.
    /// </summary>
    protected override void OnActivate()
    {
        // Border components are rendered through the IDrawable interface
        // when the renderer walks the component tree
    }

    /// <summary>
    /// Render event handler - Implements actual rendering behavior.
    /// Called automatically when the renderer walks the component tree via viewports.
    /// </summary>
    private void OnRender(object sender, EventArgs e)
    {
        if (!IsVisible() || Opacity <= 0.0f)
            return;

        switch (Style)
        {
            case BorderStyle.Rectangle:
                RenderRectangle();
                break;

            case BorderStyle.RoundedRect:
                RenderRoundedRectangle();
                break;

            case BorderStyle.Image:
                RenderImage();
                break;

            case BorderStyle.NinePatch:
                RenderNinePatch();
                break;
        }
    }

    private void RenderRectangle()
    {
        // TODO: Implement rectangle rendering using IGraphicsRenderContext.DrawRectangle
        // This will require:
        // 1. Get component bounds from Transform
        // 2. Draw background rectangle if BackgroundColor != Transparent
        // 3. Draw border rectangles if BorderThickness > 0

        // Placeholder implementation
    }

    private void RenderRoundedRectangle()
    {
        // TODO: Future implementation for rounded corners
    }

    private void RenderImage()
    {
        // TODO: Future implementation for image backgrounds
    }

    private void RenderNinePatch()
    {
        // TODO: Future implementation for ninepatch borders
    }

    private void OnRenderPropertiesChanged()
    {
        RenderPropertiesChanged?.Invoke(this, EventArgs.Empty);
    }

    public override IEnumerable<DrawCommand> GetDrawCommands(RenderContext context) => [];
}
